// Generated by CoffeeScript 1.6.2
var genericAdt, getPlatformForTarget, path;

genericAdt = require('./utils/genericAdt');

getPlatformForTarget = require('./utils').getPlatformForTarget;

path = require('path');

module.exports = function(args, root, onComplete) {
  var command, ending, platform;

  command = "installApp";
  platform = getPlatformForTarget(args.target);
  if (platform != null) {
    ending = platform === "android" ? "apk" : "ipa";
    return genericAdt.executeWithPlatform(command, {
      "package": path.resolve(path.resolve(root, path.dirname(args.output), path.basename(args.output, "." + ending) + ("." + ending)))
    }, args, root, platform, onComplete);
  } else {
    return onComplete(new Error("Don't now how to " + command + " -target='" + args.target + "'"));
  }
};
