// Generated by CoffeeScript 1.6.2
module.exports = function(args, path, onComplete) {
  var start,
    _this = this;

  start = Date.now();
  return this.reinstallAir(args, path, function(error, packageResult) {
    if (error) {
      return onComplete(error);
    } else {
      return _this.launchAir(args, path, function(error, result) {
        if (error) {
          return onComplete(error);
        } else {
          result.parts.unshift(packageResult);
          result.duration = Date.now() - start;
          return onComplete(null, result);
        }
      });
    }
  });
};
