// Generated by CoffeeScript 1.6.2
var installAir, uninstallAir;

uninstallAir = require('./uninstallAir');

installAir = require('./installAir');

module.exports = function(args, root, onComplete) {
  var results, start;

  start = Date.now();
  results = {
    parts: []
  };
  return uninstallAir(args, root, function(error, result) {
    results.parts.push(result);
    return installAir(args, root, function(error, result) {
      if (error != null) {
        return onComplete(error);
      } else {
        results.parts.push(result);
        results.duration = Date.now() - start;
        return onComplete(null, results);
      }
    });
  });
};
