// Generated by CoffeeScript 1.6.2
var exec, getFlexHome, runUnitTest;

runUnitTest = require('./runUnitTest');

exec = require('child_process').exec;

getFlexHome = require('./utils').getFlexHome;

module.exports = function(args, path, onComplete) {
  var cmd, e, flexHome;

  try {
    flexHome = getFlexHome(args);
  } catch (_error) {
    e = _error;
    onComplete(e);
    return;
  }
  cmd = function(onComplete) {
    try {
      cmd = "" + flexHome + "/bin/adl " + args.descriptor + " -profile extendedDesktop";
      console.info(cmd, path);
      return exec(cmd, {
        cwd: path
      }, onComplete);
    } catch (_error) {
      e = _error;
      console.error(e.stack);
      return onComplete(e);
    }
  };
  return runUnitTest(cmd, onComplete);
};
