// Generated by CoffeeScript 1.6.2
var exec, getFlexHome, path, runUnitTest;

runUnitTest = require('./runUnitTest');

path = require('path');

exec = require('child_process').exec;

getFlexHome = require('./utils').getFlexHome;

module.exports = function(args, cwd, onComplete) {
  var cmd, e, flexHome;

  try {
    flexHome = getFlexHome(args);
  } catch (_error) {
    e = _error;
    onComplete(e);
    return;
  }
  cmd = function(onComplete) {
    var appXml, appXmlFile;

    try {
      appXml = path.resolve(cwd, args.descriptor);
      appXmlFile = path.basename(appXml);
      cwd = path.dirname(appXml);
      cmd = "" + flexHome + "/bin/adl " + appXmlFile + " -profile extendedDesktop";
      console.info(cmd, cwd);
      return exec(cmd, {
        cwd: cwd
      }, onComplete);
    } catch (_error) {
      e = _error;
      console.error(e.stack);
      return onComplete(e);
    }
  };
  return runUnitTest(cmd, onComplete);
};
