// Generated by CoffeeScript 1.6.2
var addRegularArgument,
  __slice = [].slice;

addRegularArgument = require('./addRegularArgument');

module.exports = function() {
  var argList, args, ignore, name, separator, value;

  args = arguments[0], argList = arguments[1], separator = arguments[2], ignore = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
  for (name in args) {
    value = args[name];
    if (ignore.indexOf(name) === -1) {
      argList.push(addRegularArgument(name, value, separator));
    }
  }
  return argList;
};
