// Generated by CoffeeScript 1.6.2
var inQuotes;

inQuotes = require('./inQuotes');

module.exports = function(input) {
  var part, pos, result, _i, _len;

  result = [];
  if (input != null) {
    for (pos = _i = 0, _len = input.length; _i < _len; pos = ++_i) {
      part = input[pos];
      result[pos] = inQuotes(part);
    }
  }
  return result;
};
