// Generated by CoffeeScript 1.6.2
var exec;

exec = require('child_process').exec;

module.exports = function(jar, args, root, onComplete) {
  var cmd, start;

  start = Date.now();
  cmd = "java -Xmx384m -Djava.awt.headless=true -Dsun.io.useCanonCaches=false -jar \"" + jar + "\" " + args;
  console.info(cmd);
  return exec(cmd, {
    cwd: root
  }, function(error, stdout, stderr) {
    var result;

    if (onComplete) {
      result = {
        cmd: cmd,
        error: error,
        stderr: stderr,
        stdout: stdout,
        path: root,
        duration: Date.now() - start
      };
      if (error) {
        return onComplete(result, null);
      } else {
        return onComplete(null, result);
      }
    } else {
      if (error) {
        return console.error(stderr);
      } else {
        return console.info(stdout);
      }
    }
  });
};
