// Generated by CoffeeScript 1.6.2
var addRegularArguments, deepExtend, exec, executeJar, executeWithPlatform, getFlexHome, getPlatformForTarget;

addRegularArguments = require('./addRegularArguments');

deepExtend = require('./deepExtend');

executeJar = require('./executeJar');

getFlexHome = require('./getFlexHome');

getPlatformForTarget = require('./getPlatformForTarget');

exec = require('child_process').exec;

executeWithPlatform = function(command, commandArgs, args, root, platform, onComplete) {
  var addArgs;

  addArgs = {};
  addArgs[command] = null;
  addArgs.platform = platform;
  if (args.device) {
    addArgs.device = args.device;
  }
  return executeJar(getFlexHome(args) + "/lib/adt.jar", addRegularArguments(deepExtend(addArgs, commandArgs), [], " ").join(" "), root, onComplete);
};

module.exports = {
  executeWithPlatform: executeWithPlatform,
  execute: function(command, commandArgs, args, root, onComplete) {
    var platform;

    platform = getPlatformForTarget(args.target);
    if (platform != null) {
      return executeWithPlatform(command, commandArgs, args, root, platform, onComplete);
    } else {
      return onComplete(new Error("Don't now how to " + command + " -target='" + args.target + "'"));
    }
  }
};
