// Generated by CoffeeScript 1.6.2
module.exports = function(args) {
  var e, flexHome;

  flexHome = args.flexHome || process.env.FLEX_HOME;
  try {
    if (!flexHome) {
      throw new Error("Set the environment variable 'FLEX_HOME' to a valid flex sdk");
    }
  } catch (_error) {
    e = _error;
    throw e;
  }
  return flexHome;
};
