// Generated by CoffeeScript 1.6.2
var packageTargets;

packageTargets = require('./packageTargets');

module.exports = function(target) {
  if (packageTargets.android.indexOf(target) !== -1) {
    return 'android';
  } else if (packageTargets.ios.indexOf(target) !== -1) {
    return 'ios';
  }
};
