// Generated by CoffeeScript 1.6.2
var pushToMember;

pushToMember = require('./pushToMember');

module.exports = function(target, member, value) {
  var childName, childNode, dotIndex;

  dotIndex = member.indexOf(".");
  if (dotIndex !== -1) {
    childName = member.substring(0, dotIndex);
    member = member.substring(dotIndex + 1);
    childNode = target[childName] || (target[childName] = {});
    return pushToMember(childNode, member, value);
  } else {
    return pushToMember(target, member, value);
  }
};
