// Generated by CoffeeScript 1.6.2
var cache, fs, path;

fs = require("fs");

path = require('path');

cache = {};

module.exports = function(path) {
  var e, stat, target;

  try {
    target = cache[path];
    if (!target) {
      stat = fs.lstatSync(path);
      if (stat.isSymbolicLink()) {
        target = fs.readlinkSync(path);
      } else {
        target = path;
      }
      cache[path] = target;
    }
    return target;
  } catch (_error) {
    e = _error;
    return path;
  }
};
